### ISSUE TITLE
Throwing an error on terraform v0.12.7

### ISSUE THREAD

**Issue by claudiopalmeira** [iplabs/terraform-kubernetes-alb-ingress-controller#1]
When executing terraform init, the folllowing error is thrown
`Error: Invalid argument name

  on .terraform/modules/alb.alb-ingress-controller/iplabs-terraform-kubernetes-alb-ingress-controller-2671b50/main.tf line 171, in resource "kubernete_account" "this":
 171:       "app"      = "aws-alb-ingress-controller"

Argument names must not be quoted.
`
How do we fix this?

**Comment by headcr4sh** [comment]
I have just updated the syntax of the module to be compatible with Terraform 0.12 syntax.
Use the latest version (2.0.0) to use the module in conjunction with Terraform >=0.12.
